const items = [
    {
        id: '001',
        image: 'images/1.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        category : 'women',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'images/2.jpg',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        category : 'women',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/3.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        category : 'women',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images/4.jpg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        category : 'men',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/5.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/6.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        category : 'men',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'images/7.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        category : 'men',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/8.jpg',
        company: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        category : 'beauty',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '009',
        image: 'images/9.webp',
        company: 'DOT & KEY',
        item_name: 'Watermelon Sunscreen SPF 50++',
        category : 'beauty',
        original_price: 445,
        current_price: 395,
        discount_percentage: 11,
        return_period: 14,
        delivery_date: '20 May 2026',
        rating: {
            stars: 4.2,
            count: 2600,
        },
    },
    {
        id: '010',
        image: 'images/10.webp',
        company: 'Mamaearth',
        item_name: 'Moisture matte pink tulip',
        category : 'beauty',
        original_price: 349,
        current_price: 311,
        discount_percentage: 11,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 3.9,
            count: 1400,
        },
    },
    {
        id: '011',
        image: 'images/11.webp',
        company: 'Nauti Nati',
        item_name: 'Embrodered cotton A-line Dress',
        category: 'kids',
        original_price: 1699,
        current_price: 799,
        discount_percentage: 53,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 4.1,
            count: 652,
        },
    },
    {
        id: '012',
        image: 'images/12.webp',
        company: 'BAESD',
        item_name: 'Polka Dot Fit & Flare Dress',
        category : 'kids',
        original_price: 1999,
        current_price: 480,
        discount_percentage: 76,
        return_period: 10,
        delivery_date: '12 May 2026',
        rating: {
            stars: 4.1,
            count: 230,
        },
    },
    {
        id: '013',
        image: 'images/13.webp',
        company: 'CG Homes',
        item_name: 'Microfiber King Bedsheet with Pillowcase',
        category : 'home',
        original_price: 2499,
        current_price: 454,
        discount_percentage: 82,
        return_period: 11,
        delivery_date: '12 May 2026',
        rating: {
            stars: 3.8,
            count: 47,
        },
    },
    {
        id: '014',
        image: 'images/14.webp',
        company: 'StyleCast',
        item_name: 'Men Baggy Fit Mid-Rise Jeans',
        category : 'genz',
        original_price: 1699,
        current_price: 798,
        discount_percentage: 53,
        return_period: 14,
        delivery_date: '12 May 2026',
        rating: {
            stars: 4.1,
            count: 900,
        },
    }
];